namespace: mealie
replicaCount: 1


image:
  repository: ghcr.io/mealie-recipes/mealie
  tag: v2.8.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9000
  nodePort: 30900

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 500Mi

resoures: {}

env: []
