namespace: mealie
replicaCount: 2


image:
  repository: ghcr.io/mealie-recipes/mealie
  tag: v2.8.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000
  targetPort: 30900

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 500Mi


ingress:
  enabled: true
  className: traefik
  annotations: {}
  hosts:
    - host: mealie.local
      paths:
        - path: /
          pathType: Prefix
  tls: []


resoures: {}

env: []
