apiVersion: batch/v1
kind: Job
metadata:
  name: mealie-pre-install
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: init
          image: busybox
          command: ["sh", "-c", "echo Pre-install tasks"]
      restartPolicy: Never

