apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: {{ .Values.namespace }}
  labels:
    app: mealie
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: mealie

